version: "3.7"
services:
 mongo:
  image: mongo
  container_name: mongokanojo
  restart: always
  environment:
   - MONGO_INITDB_ROOT_USERNAME=example
   - MONGO_INITDB_ROOT_PASSWORD=example
  volumes:
   - /path/to/store/db/data:/data/db

 kanojo:
  image: wegotshrimp/barcodekanojo
  container_name: barcodekanojo
  depends_on:
   - "mongo"
  ports:
   - "5000:5000"
  environment:
   - PORT_VAL=5000
   - HTTPS=False
   - MONGO_USERNAME=example
   - MONGO_PASSWORD=example
   - MONGO_HOST=example
   - MONGO_PORT=27017
